---
# tasks file to install packages without having to set the package manager
- name: install multiple packages
  become: true # now required since the playbook set it to false
  ansible.builtin.package:
    name:
      - xclip # Todo: reinstall vim & nvim and check which clipboard mgr is installed
      - htop # Todo: learn & update flashcard
      - gparted
      - gnome-disk-utility
      # - neofetch
      - btrfs-assistant # Fedora only
      - prename # Fedora only
      - thunderbird
      - git
      # - ffmpeg-free   # cinnamon only
      - hunspell-fr
      - libreoffice-langpack-fr
      - hyphen-fr
      - libreoffice-grammalecte
      - meld # for Gnome
      - levien-inconsolata-fonts # necessary for calibre
      - calibre
      - torbrowser-launcher.noarch
      - numberstation # 2FA authenticator for github.com
      - bleachbit # clean system's and packages' cache, cookies, ...
      - filezilla
      - rubygem-asciidoctor
      - transmission
      - audacity
      - tldr
      - gimp
      - kdenlive
      # - discord
      - dolphin
      - gnome-calculator
      - arp-scan
      - klavaro # typing tutor
      - ktouch # typing tutor
      - inkscape
      - mpv
      - yt-dlp

    state: latest
